package com.totyu.totyudemo.mapper;

import com.totyu.totyudemo.entity.Class;

import java.util.List;

public interface ClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbg.generated Tue Jun 29 13:39:45 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbg.generated Tue Jun 29 13:39:45 CST 2021
     */
    int insert(Class record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbg.generated Tue Jun 29 13:39:45 CST 2021
     */
    Class selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbg.generated Tue Jun 29 13:39:45 CST 2021
     */
    List<Class> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbg.generated Tue Jun 29 13:39:45 CST 2021
     */
    int updateByPrimaryKey(Class record);
}