package com.totyu.totyudemo.mapper;

import com.totyu.totyudemo.entity.PersonRelation;

import java.util.List;

public interface PersonRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_relation
     *
     * @mbg.generated Tue Jun 29 13:39:45 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_relation
     *
     * @mbg.generated Tue Jun 29 13:39:45 CST 2021
     */
    int insert(PersonRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_relation
     *
     * @mbg.generated Tue Jun 29 13:39:45 CST 2021
     */
    PersonRelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_relation
     *
     * @mbg.generated Tue Jun 29 13:39:45 CST 2021
     */
    List<PersonRelation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_relation
     *
     * @mbg.generated Tue Jun 29 13:39:45 CST 2021
     */
    int updateByPrimaryKey(PersonRelation record);
}