package com.totyu.totyudemo.entity;

public class Class {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.id
     *
     * @mbg.generated Tue Jun 29 13:39:45 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.name
     *
     * @mbg.generated Tue Jun 29 13:39:45 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.grade
     *
     * @mbg.generated Tue Jun 29 13:39:45 CST 2021
     */
    private Integer grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.teacher_id
     *
     * @mbg.generated Tue Jun 29 13:39:45 CST 2021
     */
    private Integer teacherId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.id
     *
     * @return the value of class.id
     *
     * @mbg.generated Tue Jun 29 13:39:45 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.id
     *
     * @param id the value for class.id
     *
     * @mbg.generated Tue Jun 29 13:39:45 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.name
     *
     * @return the value of class.name
     *
     * @mbg.generated Tue Jun 29 13:39:45 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.name
     *
     * @param name the value for class.name
     *
     * @mbg.generated Tue Jun 29 13:39:45 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.grade
     *
     * @return the value of class.grade
     *
     * @mbg.generated Tue Jun 29 13:39:45 CST 2021
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.grade
     *
     * @param grade the value for class.grade
     *
     * @mbg.generated Tue Jun 29 13:39:45 CST 2021
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.teacher_id
     *
     * @return the value of class.teacher_id
     *
     * @mbg.generated Tue Jun 29 13:39:45 CST 2021
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.teacher_id
     *
     * @param teacherId the value for class.teacher_id
     *
     * @mbg.generated Tue Jun 29 13:39:45 CST 2021
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }
}