package com.totyu.totyudemo.entity;

public class PersonRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_relation.id
     *
     * @mbg.generated Tue Jun 29 13:39:45 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_relation.class_id
     *
     * @mbg.generated Tue Jun 29 13:39:45 CST 2021
     */
    private Integer classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_relation.category
     *
     * @mbg.generated Tue Jun 29 13:39:45 CST 2021
     */
    private Integer category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_relation.person_id
     *
     * @mbg.generated Tue Jun 29 13:39:45 CST 2021
     */
    private Integer personId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_relation.id
     *
     * @return the value of person_relation.id
     *
     * @mbg.generated Tue Jun 29 13:39:45 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_relation.id
     *
     * @param id the value for person_relation.id
     *
     * @mbg.generated Tue Jun 29 13:39:45 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_relation.class_id
     *
     * @return the value of person_relation.class_id
     *
     * @mbg.generated Tue Jun 29 13:39:45 CST 2021
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_relation.class_id
     *
     * @param classId the value for person_relation.class_id
     *
     * @mbg.generated Tue Jun 29 13:39:45 CST 2021
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_relation.category
     *
     * @return the value of person_relation.category
     *
     * @mbg.generated Tue Jun 29 13:39:45 CST 2021
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_relation.category
     *
     * @param category the value for person_relation.category
     *
     * @mbg.generated Tue Jun 29 13:39:45 CST 2021
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_relation.person_id
     *
     * @return the value of person_relation.person_id
     *
     * @mbg.generated Tue Jun 29 13:39:45 CST 2021
     */
    public Integer getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_relation.person_id
     *
     * @param personId the value for person_relation.person_id
     *
     * @mbg.generated Tue Jun 29 13:39:45 CST 2021
     */
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }
}